var imageLibs=require("./lib/imageLibs");
var images=require("./lib/images");
var customer=require("./lib/customer");
var users=require("./lib/users");
var httpget=require("./lib/httpget");
var oauth=require("./lib/oauth");
var verifyCode=require("./lib/verifycode");
var product=require("./lib/product");
var album=require("./lib/album");

exports.Customer=customer;
exports.ImageLibs=imageLibs;
exports.Images=images;
exports.Users=users;
exports.HttpGet=httpget;
exports.Oauth=oauth;
exports.VerifyCode=verifyCode;
exports.Product=product;
exports.Album=album;
